**Assignment 1**

1.Create & Reshape Magic

Task:

● Create an array from 1 to 12

● Convert it into a 3×4 matrix

● Print:

○ Shape

○ Number of elements

○ Data type

Hint:

Think about arange() and how reshape(rows, columns) works.

In [ ]:
import numpy as np

In [ ]:
arr=np.arange(1,13)

In [ ]:
arr1=arr.reshape(3,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr1.shape

(3, 4)

In [ ]:
arr1.size

12

In [ ]:
arr1.dtype

dtype('int64')

2.Even Number Finder

Task:

● Create numbers from 1 to 20.

● Print only even numbers.

● Print how many even numbers are there.

Hint:

Use a condition like number % 2 == 0 inside square brackets.

In [ ]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
arr1=arr[arr%2==0]
arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr1.size

10

3.Row Sum Challenge

Task:

● Create a 3×3 random integer matrix (values between 1–10).

● Print row sums.

● Print column sums.

● Print total sum.

Hint:

Look at the axis parameter. One axis works row-wise, the other column-wise.


In [ ]:
arr=np.arange(1,10)
arr1=arr.reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.sum(arr1,axis=1)

array([ 6, 15, 24])

In [ ]:
np.sum(arr1,axis=0)

array([12, 15, 18])

In [ ]:
np.sum(arr1)

np.int64(45)

4.Maximum Finder

Task:

● Create a 4×4 random matrix.

● Find the maximum value.

● Find its position (row, column).

Hint:

First find the index in flattened form, then convert it back to row and column.

In [ ]:
arr=np.arange(5,21)
arr1=arr.reshape(4,4)
arr1

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
max_value = np.max(arr1)
print("Maximum value:" ,max_value)

Maximum value: 20


In [ ]:
max_index_flat = np.argmax(arr1)
max_position = np.unravel_index(max_index_flat, arr1.shape)
print("Position of maximum value (row, column):", max_position)

Position of maximum value (row, column): (np.int64(3), np.int64(3))


5.Replace Using Condition

Task:

● Create numbers from 1 to 15.

● Replace all numbers divisible by 3 with -1.

Hint:

Select elements using a condition and assign a new value directly


In [ ]:
arr=np.arange(1,16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
arr[arr % 3 == 0] = -1
print(arr)

[ 1  2 -1  4  5 -1  7  8 -1 10 11 -1 13 14 -1]


6.Simple Matrix Operations

Task:

● Create two 3×3 random matrices.

● Add them.

● Multiply them element-wise.

● Multiply them using matrix multiplication.

Hint:

There is a difference between * and @.

In [ ]:
import numpy as np

m1= np.arange(1,10)
m2= np.arange(11,20)
m1=m1.reshape(3,3)
m2=m2.reshape(3,3)
print(m1)
print(m2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [ ]:
sum_matrices = m1 + m2
print("\nSum of matrices:\n",sum_matrices)


Sum of matrices:
 [[12 14 16]
 [18 20 22]
 [24 26 28]]


In [ ]:
element_wise = m1 * m2
print("Element-wise product:\n",element_wise)

Element-wise product:
 [[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [ ]:
m1.dot(m2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

7.Mini ML Style Question

Task:

 Given:

 X = np.array([[2, 3],
            [4, 5],
                       [6, 7]])

                      Multiply each row by 10 without using loops.
                       Expected output:
                       [[20 30]
                        [40 50]
                         [60 70]]
                         Hint:
                          When multiplying an array by a number, NumPy automatically applies it to every element.

In [ ]:
x=np.arange(2,8)
x

array([2, 3, 4, 5, 6, 7])

In [ ]:
arr=x.reshape(3,2)
arr

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
arr1=arr*10
arr1

array([[20, 30],
       [40, 50],
       [60, 70]])

8.Filter Rows Based on Condition

Task:

● Create a 5×3 random matrix (values between 0–20).

● Print only rows where row sum > 30.

Hint:

 First compute row sums. Then use that result as a mask to filter rows.

In [ ]:
Arr=np.array([[5,12, 3],[19,6,1],[8,9,3],[11,7,10],[14,2,15]])

In [ ]:
Arr

array([[ 5, 12,  3],
       [19,  6,  1],
       [ 8,  9,  3],
       [11,  7, 10],
       [14,  2, 15]])

In [ ]:
Sum=np.sum(Arr, axis=1)
Sum

array([20, 26, 20, 28, 31])

In [ ]:
Arr1=Sum[Sum>30]

In [ ]:
Arr1

array([31])

9.Reverse an Array

Task:

● Create numbers from 1 to 10.

● Reverse the array using slicing.

Hint:

Slicing supports a negative step value.

In [ ]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[9::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

10.Simple Normalization

Task:

● Create a 3×3 random matrix.

● Divide each row by its row sum.

Hint:

Row sums need to keep their 2D shape so broadcasting works properly.

In [ ]:
import numpy as np

A = np.random.randint(1, 10, (3, 3))

row_sum = A.sum(axis=1, keepdims=True)

normalized = A / row_sum

print(normalized)

[[0.25       0.41666667 0.33333333]
 [0.35294118 0.29411765 0.35294118]
 [0.28571429 0.42857143 0.28571429]]


Bonus


1. Swap first and last column of a matrix.

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

A[:, [0, -1]] = A[:, [-1, 0]]

print(A)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


2. Create a 4×4 identity matrix.

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

3. Create a 5×5 matrix filled with zeros except the border filled with 1.

In [ ]:
A = np.zeros((5, 5), dtype=int)

A[0, :] = 1
A[-1, :] = 1
A[:, 0] = 1
A[:, -1] = 1

print(A)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
